// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: reproductor_mp3

#include "ui.h"

lv_obj_t * ui_Archivos = NULL;
lv_obj_t * ui_ContStatusBar1 = NULL;
lv_obj_t * ui_PnlCounterInfo = NULL;
lv_obj_t * ui_LblFileCounter = NULL;
lv_obj_t * ui_PnlFileList = NULL;
// event funtions

// build funtions

void ui_Archivos_screen_init(void)
{
    ui_Archivos = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Archivos, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Archivos, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Archivos, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContStatusBar1 = ui_ContStatusBar_create(ui_Archivos);
    lv_obj_set_x(ui_ContStatusBar1, 0);
    lv_obj_set_y(ui_ContStatusBar1, 0);

    ui_PnlCounterInfo = lv_obj_create(ui_Archivos);
    lv_obj_set_width(ui_PnlCounterInfo, 230);
    lv_obj_set_height(ui_PnlCounterInfo, 20);
    lv_obj_set_x(ui_PnlCounterInfo, 0);
    lv_obj_set_y(ui_PnlCounterInfo, 25);
    lv_obj_set_align(ui_PnlCounterInfo, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PnlCounterInfo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_PnlCounterInfo, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblFileCounter = lv_label_create(ui_PnlCounterInfo);
    lv_obj_set_width(ui_LblFileCounter, lv_pct(100));
    lv_obj_set_height(ui_LblFileCounter, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblFileCounter, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_LblFileCounter, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_LblFileCounter, "Elemento 45 de 918");
    lv_obj_set_style_text_align(ui_LblFileCounter, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_LblFileCounter, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblFileCounter, &ui_font_Regular14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PnlFileList = lv_obj_create(ui_Archivos);
    lv_obj_set_width(ui_PnlFileList, 230);
    lv_obj_set_height(ui_PnlFileList, 220);
    lv_obj_set_x(ui_PnlFileList, 0);
    lv_obj_set_y(ui_PnlFileList, 50);
    lv_obj_set_align(ui_PnlFileList, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_PnlFileList, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PnlFileList, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PnlFileList, LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_style_clip_corner(ui_PnlFileList, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PnlFileList, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PnlFileList, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PnlFileList, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Archivos_screen_destroy(void)
{
    if(ui_Archivos) lv_obj_del(ui_Archivos);

    // NULL screen variables
    ui_Archivos = NULL;
    ui_ContStatusBar1 = NULL;
    ui_PnlCounterInfo = NULL;
    ui_LblFileCounter = NULL;
    ui_PnlFileList = NULL;

}
