// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: reproductor_mp3

#ifndef UI_ARCHIVOS_H
#define UI_ARCHIVOS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Archivos
extern void ui_Archivos_screen_init(void);
extern void ui_Archivos_screen_destroy(void);
extern lv_obj_t * ui_Archivos;
extern lv_obj_t * ui_ContStatusBar2;
extern lv_obj_t * ui_LblBatteryPct2;
extern lv_obj_t * ui_ImgBatteryIcon2;
extern lv_obj_t * ui_ImgBatteryCharging2;
extern lv_obj_t * ui_ContMainList;
extern lv_obj_t * ui_LblCurrentPath;
extern lv_obj_t * ui_PnlFileList;
extern lv_obj_t * ui_FileItemExample;
extern lv_obj_t * ui_FileItemExample1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

