// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: reproductor_mp3

#include "ui.h"

void ui_comp_ContStatusBar_create_hook(lv_obj_t * comp)
{
}
