// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: reproductor_mp3

#ifndef _UI_COMP_FILEITEM_H
#define _UI_COMP_FILEITEM_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT FileItem
#define UI_COMP_FILEITEM_FILEITEM 0
#define UI_COMP_FILEITEM_IMGFILEICON 1
#define UI_COMP_FILEITEM_LBLFILENAME 2
#define _UI_COMP_FILEITEM_NUM 3
lv_obj_t * ui_FileItem_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
