// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: reproductor_mp3

#include "ui.h"

// COMPONENT FileItem

lv_obj_t * ui_FileItem_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_FileItem;
    cui_FileItem = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_FileItem);
    lv_obj_set_width(cui_FileItem, lv_pct(100));
    lv_obj_set_height(cui_FileItem, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(cui_FileItem, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_FileItem, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_FileItem, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(cui_FileItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_FileItem, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_FileItem, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_FileItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_FileItem, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_FileItem, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_FileItem, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_FileItem, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_FileItem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_FileItem, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(cui_FileItem, 10, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(cui_FileItem, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(cui_FileItem, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_left(cui_FileItem, 5, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_right(cui_FileItem, 5, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_top(cui_FileItem, 5, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_bottom(cui_FileItem, 5, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_row(cui_FileItem, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_pad_column(cui_FileItem, 10, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_t * cui_ImgFileIcon;
    cui_ImgFileIcon = lv_img_create(cui_FileItem);
    lv_obj_set_width(cui_ImgFileIcon, LV_SIZE_CONTENT);   /// 16
    lv_obj_set_height(cui_ImgFileIcon, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_align(cui_ImgFileIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_ImgFileIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_ImgFileIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(cui_ImgFileIcon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(cui_ImgFileIcon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_LblFileName;
    cui_LblFileName = lv_label_create(cui_FileItem);
    lv_obj_set_height(cui_LblFileName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_grow(cui_LblFileName, 1);
    lv_obj_set_align(cui_LblFileName, LV_ALIGN_CENTER);
    lv_label_set_text(cui_LblFileName, "Bring Me The Horizon - Can You Feel My Heart.mp3");
    lv_obj_set_style_text_font(cui_LblFileName, &ui_font_Regular14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_FILEITEM_NUM);
    children[UI_COMP_FILEITEM_FILEITEM] = cui_FileItem;
    children[UI_COMP_FILEITEM_IMGFILEICON] = cui_ImgFileIcon;
    children[UI_COMP_FILEITEM_LBLFILENAME] = cui_LblFileName;
    lv_obj_add_event_cb(cui_FileItem, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_FileItem, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_FileItem_create_hook(cui_FileItem);
    return cui_FileItem;
}

