// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: reproductor_mp3

#ifndef _UI_COMP_CONTSTATUSBAR_H
#define _UI_COMP_CONTSTATUSBAR_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT ContStatusBar
#define UI_COMP_CONTSTATUSBAR_CONTSTATUSBAR 0
#define UI_COMP_CONTSTATUSBAR_LBLBATTERYPCT 1
#define UI_COMP_CONTSTATUSBAR_IMGBATTERYICON 2
#define _UI_COMP_CONTSTATUSBAR_NUM 3
lv_obj_t * ui_ContStatusBar_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
