// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: reproductor_mp3

#include "ui.h"

// COMPONENT ContStatusBar

lv_obj_t * ui_ContStatusBar_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_ContStatusBar;
    cui_ContStatusBar = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_ContStatusBar);
    lv_obj_set_width(cui_ContStatusBar, 65);
    lv_obj_set_height(cui_ContStatusBar, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(cui_ContStatusBar, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(cui_ContStatusBar, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_ContStatusBar, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(cui_ContStatusBar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_LblBatteryPct;
    cui_LblBatteryPct = lv_label_create(cui_ContStatusBar);
    lv_obj_set_width(cui_LblBatteryPct, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(cui_LblBatteryPct, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_LblBatteryPct, -57);
    lv_obj_set_y(cui_LblBatteryPct, -130);
    lv_obj_set_align(cui_LblBatteryPct, LV_ALIGN_CENTER);
    lv_label_set_text(cui_LblBatteryPct, "67%");
    lv_obj_set_style_text_font(cui_LblBatteryPct, &ui_font_Regular14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_ImgBatteryIcon;
    cui_ImgBatteryIcon = lv_img_create(cui_ContStatusBar);
    lv_img_set_src(cui_ImgBatteryIcon, &ui_img_bateria_png);
    lv_obj_set_width(cui_ImgBatteryIcon, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(cui_ImgBatteryIcon, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_align(cui_ImgBatteryIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_ImgBatteryIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_ImgBatteryIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(cui_ImgBatteryIcon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(cui_ImgBatteryIcon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_CONTSTATUSBAR_NUM);
    children[UI_COMP_CONTSTATUSBAR_CONTSTATUSBAR] = cui_ContStatusBar;
    children[UI_COMP_CONTSTATUSBAR_LBLBATTERYPCT] = cui_LblBatteryPct;
    children[UI_COMP_CONTSTATUSBAR_IMGBATTERYICON] = cui_ImgBatteryIcon;
    lv_obj_add_event_cb(cui_ContStatusBar, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_ContStatusBar, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_ContStatusBar_create_hook(cui_ContStatusBar);
    return cui_ContStatusBar;
}

