// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: reproductor_mp3

#ifndef UI_REPRODUCTOR_H
#define UI_REPRODUCTOR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Reproductor
extern void ui_Reproductor_screen_init(void);
extern void ui_Reproductor_screen_destroy(void);
extern lv_obj_t * ui_Reproductor;
extern lv_obj_t * ui_ContStatusBar;
extern lv_obj_t * ui_PnlAlbumMask;
extern lv_obj_t * ui_LblSongTitle;
extern lv_obj_t * ui_LblArtistName;
extern lv_obj_t * ui_ContProgress;
extern lv_obj_t * ui_LblTimeCurrent;
extern lv_obj_t * ui_BarProgress;
extern lv_obj_t * ui_LblTimeTotal;
extern lv_obj_t * ui_ImgPauseIcon;
extern lv_obj_t * ui_ImgPlayIcon;
extern lv_obj_t * ui_PnlVolumeToast;
extern lv_obj_t * ui_BarVolumeLevel;
extern lv_obj_t * ui_ImgVolumeIcon;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

