// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: reproductor_mp3

#include "ui.h"

lv_obj_t * ui_Reproductor = NULL;
lv_obj_t * ui_ContStatusBar1 = NULL;
lv_obj_t * ui_LblBatteryPct1 = NULL;
lv_obj_t * ui_ImgBatteryIcon1 = NULL;
lv_obj_t * ui_PnlAlbumMask = NULL;
lv_obj_t * ui_LblSongTitle = NULL;
lv_obj_t * ui_LblArtistName = NULL;
lv_obj_t * ui_ContProgress = NULL;
lv_obj_t * ui_LblTimeCurrent = NULL;
lv_obj_t * ui_BarProgress = NULL;
lv_obj_t * ui_LblTimeTotal = NULL;
lv_obj_t * ui_ImgPauseIcon = NULL;
lv_obj_t * ui_ImgPlayIcon = NULL;
lv_obj_t * ui_PnlVolumeToast = NULL;
lv_obj_t * ui_BarVolumeLevel = NULL;
lv_obj_t * ui_ImgVolumeIcon = NULL;
// event funtions
void ui_event_Reproductor(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_Archivos, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 1000, &ui_Archivos_screen_init);
    }
}

// build funtions

void ui_Reproductor_screen_init(void)
{
    ui_Reproductor = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Reproductor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Reproductor, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Reproductor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContStatusBar1 = lv_obj_create(ui_Reproductor);
    lv_obj_remove_style_all(ui_ContStatusBar1);
    lv_obj_set_width(ui_ContStatusBar1, 65);
    lv_obj_set_height(ui_ContStatusBar1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_ContStatusBar1, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_ContStatusBar1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ContStatusBar1, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_ContStatusBar1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LblBatteryPct1 = lv_label_create(ui_ContStatusBar1);
    lv_obj_set_width(ui_LblBatteryPct1, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_LblBatteryPct1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblBatteryPct1, -57);
    lv_obj_set_y(ui_LblBatteryPct1, -130);
    lv_obj_set_align(ui_LblBatteryPct1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblBatteryPct1, "67%");
    lv_obj_set_style_text_font(ui_LblBatteryPct1, &ui_font_Regular14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgBatteryIcon1 = lv_img_create(ui_ContStatusBar1);
    lv_img_set_src(ui_ImgBatteryIcon1, &ui_img_bateria_png);
    lv_obj_set_width(ui_ImgBatteryIcon1, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_ImgBatteryIcon1, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_align(ui_ImgBatteryIcon1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgBatteryIcon1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgBatteryIcon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_ImgBatteryIcon1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ImgBatteryIcon1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PnlAlbumMask = lv_obj_create(ui_Reproductor);
    lv_obj_set_width(ui_PnlAlbumMask, 150);
    lv_obj_set_height(ui_PnlAlbumMask, 150);
    lv_obj_set_x(ui_PnlAlbumMask, 0);
    lv_obj_set_y(ui_PnlAlbumMask, 25);
    lv_obj_set_align(ui_PnlAlbumMask, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PnlAlbumMask, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PnlAlbumMask, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PnlAlbumMask, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlAlbumMask, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_PnlAlbumMask, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PnlAlbumMask, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PnlAlbumMask, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblSongTitle = lv_label_create(ui_Reproductor);
    lv_obj_set_width(ui_LblSongTitle, 200);
    lv_obj_set_height(ui_LblSongTitle, 23);
    lv_obj_set_x(ui_LblSongTitle, 0);
    lv_obj_set_y(ui_LblSongTitle, -75);
    lv_obj_set_align(ui_LblSongTitle, LV_ALIGN_BOTTOM_MID);
    lv_label_set_long_mode(ui_LblSongTitle, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_LblSongTitle, "I ALWAYS WANTED TO LEAVE");
    lv_obj_set_style_text_align(ui_LblSongTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblSongTitle, &ui_font_Bold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblArtistName = lv_label_create(ui_Reproductor);
    lv_obj_set_width(ui_LblArtistName, 150);
    lv_obj_set_height(ui_LblArtistName, 16);
    lv_obj_set_x(ui_LblArtistName, 0);
    lv_obj_set_y(ui_LblArtistName, -55);
    lv_obj_set_align(ui_LblArtistName, LV_ALIGN_BOTTOM_MID);
    lv_label_set_long_mode(ui_LblArtistName, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_LblArtistName, " The Plot In You");
    lv_obj_set_style_text_align(ui_LblArtistName, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblArtistName, &ui_font_Regular14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContProgress = lv_obj_create(ui_Reproductor);
    lv_obj_remove_style_all(ui_ContProgress);
    lv_obj_set_width(ui_ContProgress, 220);
    lv_obj_set_height(ui_ContProgress, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_ContProgress, 0);
    lv_obj_set_y(ui_ContProgress, -30);
    lv_obj_set_align(ui_ContProgress, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_ContProgress, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ContProgress, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_ContProgress, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LblTimeCurrent = lv_label_create(ui_ContProgress);
    lv_obj_set_width(ui_LblTimeCurrent, 31);
    lv_obj_set_height(ui_LblTimeCurrent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblTimeCurrent, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_LblTimeCurrent, "0:41");

    ui_BarProgress = lv_bar_create(ui_ContProgress);
    lv_bar_set_value(ui_BarProgress, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BarProgress, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BarProgress, 140);
    lv_obj_set_height(ui_BarProgress, 5);
    lv_obj_set_x(ui_BarProgress, 0);
    lv_obj_set_y(ui_BarProgress, -30);
    lv_obj_set_align(ui_BarProgress, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_bg_color(ui_BarProgress, lv_color_hex(0x4C4C4C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarProgress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BarProgress, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarProgress, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_LblTimeTotal = lv_label_create(ui_ContProgress);
    lv_obj_set_width(ui_LblTimeTotal, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_LblTimeTotal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblTimeTotal, 0);
    lv_obj_set_y(ui_LblTimeTotal, -25);
    lv_obj_set_align(ui_LblTimeTotal, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_LblTimeTotal, "4:55");

    ui_ImgPauseIcon = lv_img_create(ui_Reproductor);
    lv_img_set_src(ui_ImgPauseIcon, &ui_img_pause_png);
    lv_obj_set_width(ui_ImgPauseIcon, LV_SIZE_CONTENT);   /// 16
    lv_obj_set_height(ui_ImgPauseIcon, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_ImgPauseIcon, 0);
    lv_obj_set_y(ui_ImgPauseIcon, -10);
    lv_obj_set_align(ui_ImgPauseIcon, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_ImgPauseIcon, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgPauseIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_ImgPauseIcon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ImgPauseIcon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgPlayIcon = lv_img_create(ui_Reproductor);
    lv_img_set_src(ui_ImgPlayIcon, &ui_img_play_png);
    lv_obj_set_width(ui_ImgPlayIcon, LV_SIZE_CONTENT);   /// 16
    lv_obj_set_height(ui_ImgPlayIcon, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_ImgPlayIcon, 0);
    lv_obj_set_y(ui_ImgPlayIcon, -10);
    lv_obj_set_align(ui_ImgPlayIcon, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_ImgPlayIcon, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgPlayIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_ImgPlayIcon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ImgPlayIcon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PnlVolumeToast = lv_obj_create(ui_Reproductor);
    lv_obj_set_height(ui_PnlVolumeToast, 150);
    lv_obj_set_width(ui_PnlVolumeToast, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_x(ui_PnlVolumeToast, 10);
    lv_obj_set_y(ui_PnlVolumeToast, 25);
    lv_obj_set_flex_flow(ui_PnlVolumeToast, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PnlVolumeToast, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_PnlVolumeToast, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PnlVolumeToast, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PnlVolumeToast, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlVolumeToast, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PnlVolumeToast, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PnlVolumeToast, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PnlVolumeToast, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PnlVolumeToast, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PnlVolumeToast, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarVolumeLevel = lv_bar_create(ui_PnlVolumeToast);
    lv_bar_set_value(ui_BarVolumeLevel, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BarVolumeLevel, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BarVolumeLevel, 5);
    lv_obj_set_flex_grow(ui_BarVolumeLevel, 1);
    lv_obj_set_align(ui_BarVolumeLevel, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_BarVolumeLevel, lv_color_hex(0x4C4C4C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarVolumeLevel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BarVolumeLevel, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarVolumeLevel, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_ImgVolumeIcon = lv_img_create(ui_PnlVolumeToast);
    lv_img_set_src(ui_ImgVolumeIcon, &ui_img_volume_png);
    lv_obj_set_width(ui_ImgVolumeIcon, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_ImgVolumeIcon, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_align(ui_ImgVolumeIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgVolumeIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgVolumeIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_ImgVolumeIcon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ImgVolumeIcon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Reproductor, ui_event_Reproductor, LV_EVENT_ALL, NULL);

}

void ui_Reproductor_screen_destroy(void)
{
    if(ui_Reproductor) lv_obj_del(ui_Reproductor);

    // NULL screen variables
    ui_Reproductor = NULL;
    ui_ContStatusBar1 = NULL;
    ui_LblBatteryPct1 = NULL;
    ui_ImgBatteryIcon1 = NULL;
    ui_PnlAlbumMask = NULL;
    ui_LblSongTitle = NULL;
    ui_LblArtistName = NULL;
    ui_ContProgress = NULL;
    ui_LblTimeCurrent = NULL;
    ui_BarProgress = NULL;
    ui_LblTimeTotal = NULL;
    ui_ImgPauseIcon = NULL;
    ui_ImgPlayIcon = NULL;
    ui_PnlVolumeToast = NULL;
    ui_BarVolumeLevel = NULL;
    ui_ImgVolumeIcon = NULL;

}
