[env:esp32-s3-super-mini]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
board_upload.flash_size = 4MB
board_build.partitions = huge_app.csv

; 2. Configuración de hardware para la memoria (2MB PSRAM suele ser Quad SPI)
board_build.arduino.memory_type = qio_qspi

; 3. Banderas de compilación
build_flags = 
    -D BOARD_HAS_PSRAM           ; Activa explícitamente el uso de la PSRAM
    -D ARDUINO_USB_MODE=1        ; Configura el puerto USB en modo nativo
    -D ARDUINO_USB_CDC_ON_BOOT=1 ; Redirige el Serial Monitor al USB nativo
    -D LV_CONF_INCLUDE_SIMPLE
    -I include

lib_deps =
    moononournation/GFX Library for Arduino @ ~1.4.9
    lvgl/lvgl@^8.3.11
    https://github.com/schreibfaul1/ESP32-audioI2S.git#2.0.6
